spring:
  jpa:
    show-sql: true
  application:
    name: java-advanced
  profiles:
    active: ${PROFILE:local}

jwt:
  secret: senha
  issuer: wellwork-gs
  expiration: 3600

security:
  enabled: true
